### ISSUE TITLE
Wallet Download link doesn't send user to the download block

### ISSUE THREAD

**Issue by gridcat** [gridcoin-community/Gridcoin-World-Site#10]
The `Wallet Downloads` link in the footer has #Download hash, so it should send the user directly to the Wallet Download section on the index page. It sends the user to the top of the page instead.
Please make this link redirect the user straight to the "Download" section of the page.

**Comment by RoboticMind** [comment]
Looks like the anchor tag should be `#section_download` instead

**Comment by gridcat** [comment]
@barton2526 please assign it to me
