### ISSUE TITLE
Dead links at contact us page

### ISSUE THREAD

**Issue by gridcat** [gridcoin-community/Gridcoin-World-Site#9]
Page: https://gridcoin.world/contact.htm

At contact us page we have a link to CryptoCurrenctTalk forum, which is kind a dead atm. The link redirects to bitcoin.org website.
We need to get rid of it.
https://cryptocurrencytalk.com/forum/464-gridcoin-grc/ -> https://bitcoin.org/en/

At the same page there is a link to the Security Dsclosure Document which is also sending user to 404 page.
![image](https://user-images.githubusercontent.com/32429858/144904139-bb786480-56bd-441b-8d5b-dc6d3525f923.png)
Please consider to update the link or to get rid of this line.

**Comment by barton2526** [comment]
https://github.com/gridcoin-community/Gridcoin-Site/pull/282

**Comment by gridcat** [comment]
please assign it to me
